# errata:
# - A travis bug causes caches to trample eachother when using the same
#   compiler key (which we don't use anyway). This is worked around for now by
#   replacing the "compilers" with a build name prefixed by the no-op ":"
#   command. See: https://github.com/travis-ci/travis-ci/issues/4393
# - sudo/dist/group are set so as to get Blue Box VMs, necessary for [loopback]
#   IPv6 support

sudo: required
dist: precise
group: legacy

os: linux
language: cpp
compiler: gcc
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      env: $TRAVIS_OS_NAME="linux"
#    - os: linux
#      dist: bionic
#      sudo: required
#      env: $TRAVIS_OS_NAME="win"
#    - os: osx
#      osx_image: xcode10.1
#      env: $TRAVIS_OS_NAME="osx"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool ncurses-dev unzip git python python-zmq zlib1g-dev wget curl bsdmainutils automake; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake autoconf libtool automake coreutils pkgconfig gmp wget; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc5 --without-multilib; fi
#  - if [[ "$TRAVIS_OS_NAME" == "win" ]]; then sudo apt-get update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "win" ]]; then sudo apt-get install build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool ncurses-dev unzip git python curl zlib1g-dev wget bsdmainutils automake cmake mingw-w64; fi
#  - if [[ "$TRAVIS_OS_NAME" == "win" ]]; then sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix; fi
#  - if [[ "$TRAVIS_OS_NAME" == "win" ]]; then sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./zcutil/build.sh -j4; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./zcutil/fetch-params.sh -j4; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./src/zelcash-gtest -j4; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./zcutil/build.sh -j4; fi
#  - if [[ "$TRAVIS_OS_NAME" == "win" ]]; then ./zcutil/build-win.sh -j4; fi
before_deploy:
  - strip ./src/zelcashd ./src/zelcash-cli ./src/zelcash-tx ./src/zelcash-gtest
  - cp ./src/zelcashd $HOME/zelcashd-$BRANCH-$TRAVIS_BUILD_NUMBER-travis
  - cp ./src/zelcash-cli $HOME/zelcash-cli-$BRANCH-$TRAVIS_BUILD_NUMBER-travis
  - cp ./src/zelcash-tx $HOME/zelcash-tx-$BRANCH-$TRAVIS_BUILD_NUMBER-travis
  - cp ./src/zelcash-gtest $HOME/zelcash-gtest-$BRANCH-$TRAVIS_BUILD_NUMBER-travis
deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  api_key:
    secure: B3R37GKUWzr4ZM9j/Fgr5u0jtw9CKha57O70gbgj7IkjggShhRMQuKnJrkLduSSLFyk0OtckmFlvf0UQcVW2YVJj5F9OlqEPP51tooeWT7L7kneRWX6CD23o1Y7F0JmXEIoOb+2pnlhAgtnoIwUaAbhg0iipMx5pu2RJwWuCb/7iFGtAZI5ZukKRCc+Se0tRDs/yqh6rkbbFqPgK5kk02EXV926+HKnKwzOParwRaqbdAquT1JqXTePEl+8O5RJpQdMeH1goMu3RVp+9QE9Rh3wmSjvebhBC5fE03ws/aclk0Nj5wvnI3qxDYnHHcUVXpGetGNg38xHt6NAm12m99lgadKv5QUS8sMTwjr55tTDVFlmCuM+AKXLRLsOo1ZlneacVBkRCXz7pifTAtLMKXxl08RtpTXT5xjSeoerhyellHaZAAxrlWf/XSuiBBQUFZ+MTsRxUcOPjYnT2T0tBt+7lrTsy4tQz+aITkdAxQEm64DaSdJPQGEs78NUm0FYQJnIBCAKUVnICkfRlIys3pKsmx+a7pEEWMdj+eoxnEUfYxdeRUk0YUahQgN39ChOexac4raq1tUCTpvTTDTxDmFGn7jleA+chDfnm+mMCOlKWcEYMYnQ5uP7JeFPb/H6p4X33n5343edZb1OGho6EIWADtejfm59NbBOzwH6vGpI=
  file_glob: true
  file:
  - "$HOME/zelcashd-$BRANCH-$TRAVIS_BUILD_NUMBER-travis"
  - "$HOME/zelcash-cli-$BRANCH-$TRAVIS_BUILD_NUMBER-travis"
  - "$HOME/zelcash-tx-$BRANCH-$TRAVIS_BUILD_NUMBER-travis"
  - "$HOME/zelcash-gtest-$BRANCH-$TRAVIS_BUILD_NUMBER-travis"
  on:
    repo: zelcash/zelcash
    all_branches: true